# Generated by Django 5.0 on 2023-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(unique=True, verbose_name='email address'),
        ),
    ]
