# Generated by Django 5.0 on 2023-12-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
