# Generated by Django 5.0 on 2023-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_adressuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressuser',
            name='ZipCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adressuser',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
