# Generated by Django 5.0 on 2023-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_adressuser_zipcode_adressuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressuser',
            name='title',
            field=models.CharField(),
        ),
    ]
