# Generated by Django 5.0 on 2023-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'زن'), (0, 'مرد')]),
        ),
    ]
