# Generated by Django 5.0 on 2023-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(choices=[('1', 'زن'), ('0', 'مرد')]),
        ),
    ]
