# Generated by Django 5.0 on 2023-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('code', models.IntegerField()),
                ('ExceptionDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
