# Generated by Django 5.0 on 2023-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_forgetpassuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassuser',
            name='ExpireTime',
            field=models.DateTimeField(),
        ),
    ]
