# Generated by Django 5.0 on 2023-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('descriptiom', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/image')),
            ],
        ),
    ]
