# Generated by Django 5.0 on 2023-12-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorey',
            field=models.ManyToManyField(to='product.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
