# Generated by Django 5.0 on 2023-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_categorey_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorey',
            field=models.ManyToManyField(related_name='products', to='product.categories'),
        ),
    ]
