# Generated by Django 5.0 on 2023-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_categorey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
