# Generated by Django 5.0 on 2023-12-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_color_size_product_color_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.product')),
            ],
        ),
    ]
