# Generated by Django 5.0 on 2023-12-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0013_alter_product_color_alter_product_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountName', models.CharField(max_length=10, unique=True)),
                ('DiscountPercent', models.SmallIntegerField()),
                ('Expiredate', models.DateTimeField()),
                ('Quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orderid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetailuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('createDate', models.DateField(null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDtailid', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDtailid', to=settings.AUTH_USER_MODEL)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDtailid', to='Basket.orderuser')),
            ],
        ),
    ]
